// <auto-generated />
namespace MeetingManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SecRolePermission_edited : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecRolePermission_edited));
        
        string IMigrationMetadata.Id
        {
            get { return "201901271957374_SecRolePermission_edited"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
