// <auto-generated />
namespace MeetingManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class resource_permission_statustype_Changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resource_permission_statustype_Changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201901272100456_resource_permission_statustype_Changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
