// <auto-generated />
namespace MeetingManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatedByModifiedByaddedtoMeetingResultImplementationandAgendaTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatedByModifiedByaddedtoMeetingResultImplementationandAgendaTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201904241017341_CreatedBy, ModifiedBy added to Meeting Result, Implementation and Agenda Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
