// <auto-generated />
namespace MeetingManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rolerelatedtablesaddedbymahmud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rolerelatedtablesaddedbymahmud));
        
        string IMigrationMetadata.Id
        {
            get { return "201901230434280_role related tables added by mahmud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
